#!/bin/bash
echo "VITE_SUPABASE_URL=$VITE_SUPABASE_URL"
echo "VITE_SUPABASE_ANON_KEY=$VITE_SUPABASE_ANON_KEY"
echo "SUPABASE_URL=$SUPABASE_URL"
echo "SUPABASE_SERVICE_KEY=$SUPABASE_SERVICE_KEY"
echo "VITE_APP_TITLE=StreetMarket - E-commerce Marketplace"
